//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentExtension { get; set; }
        public string DocumentPath { get; set; }
        public int StatusId { get; set; }
        public int UserId { get; set; }
        public System.DateTime LastModifiedTimestamp { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
